version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_teste
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste_fullstack
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./criar_tabela.sql:/docker-entrypoint-initdb.d/criar_tabela.sql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  php:
    build: .
    container_name: php_api
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html
    command: php -S 0.0.0.0:8080
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
